<template>
	<div>
		<transition name="fade">
			<div class="modal-overlay" id="overlay" v-if="open && slide1">
				<div class="modal-pane modal-flex">

					<div class="onboarding-main-split">

						<div class="flex-layout">

							<div class="flex-left split-left onboarding-1-bg">

														<!-- <img src="../../assets/img/Onboarding1.svg" /> -->

							</div>

							<div class="flex-right split-right">

								<h1 class="split-right-header">Welcome to SafeHold</h1>

								<p class="split-right-outter-article">SafeHold is a simple blockchain hub that allows you to mine the Ell coins also send and receive transaction on the Ellcrys Network. SafeHold enable non-technical users to interact with most of the features of the Ellcrys’s current Alphanet - <em>Inception v.0.1.x</em></p>

								<div class="split-right-main">
									<div class="article-split-wrapper">

										<div class="article">
											<div class="article-section">
												<h3>Mining Engine</h3>
												<p class="light">All operations are protected by a blockade, and this guarantees their security.</p>
											</div>

										</div>

										<div class="article">
											<div class="article-section">
												<h3>Wallet System</h3>
												<p class="light">All operations are protected by a blockade, and this guarantees their security.</p>
											</div>
										</div>

									</div>

									<p class="split-right-inner-article">It’s a simple platform that help both pre-sale contributors and the Ellcrys Miner Partnership Program participants to track and monitor their coin</p>

								</div>

								<div class="split-right-footer">
									<button class="next" @click="toNextSlide(2)">Next</button>

									<ul class="page-switcher">
										<li class="active"></li>
										<li></li>
										<li></li>
										<li></li>
									</ul>

									<button class="skip" @click="doneOnboarding()">Skip</button>
								</div>

							</div>

						</div>

					</div>

				</div>
			</div>
		</transition>

		<transition name="fade">
			<div class="modal-overlay" id="overlay" v-if="open && slide2">
				<div class="modal-pane modal-flex">

					<div class="onboarding-main-split">

						<div class="flex-layout">

							<div class="flex-left split-left onboarding-1-bg">

							</div>
							<div class="flex-right split-right">

								<h1 class="split-right-header">What is a wallet?</h1>

								<div class="split-right-main">
									<div class="article-split-wrapper">

										<div class="article">
											<div class="article-section">
												<p>Wallet is a feature tool for interacting with the Ellcrys network and using ELL as a currency. You will be able to send and receive ELL coins, as a personal record to track your transactions.</p>
											</div>

											<div class="article-section">
												<p><span>Wallets are often generated by a unique password which creates a seed phrase. The mnemonic seedphrease is a list of 12 words that can be easily written down on paper for backup.</span></p>
											</div>
										</div>

										<div class="article">
											<div class="article-section">
												<p><span>A seed works as a master key that stores all of the information</span> needed to re-create the wallet at any time even if the encryption passphrase is forgotten or the wallet is destroyed. Same seed can also be used to export your wallet to other Ellcrys wallet clients.</p>
											</div>
										</div>

									</div>

								</div>

								<div class="split-right-footer">
									<button class="next" @click="toNextSlide(3)">Next</button>

									<ul class="page-switcher">
										<li></li>
										<li class="active"></li>
										<li></li>
										<li></li>
									</ul>

									<button class="skip" @click="doneOnboarding()">Skip</button>
								</div>

							</div>

						</div>

					</div>

				</div>
			</div>
		</transition>

		<transition name="fade">
			<div class="modal-overlay" id="overlay" v-if="open && slide3">
				<div class="modal-pane modal-flex">

					<div class="onboarding-main-split">

						<div class="flex-layout">

							<div class="flex-left split-left onboarding-3-bg">

							</div>
							<div class="flex-right split-right">

								<h1 class="split-right-header">What is a desktop miner?</h1>

								<div class="split-right-main">
									<div class="article-split-wrapper">

										<div class="article">
											<div class="article-section">
												<p>A desktop miner is a key feature tool for mining (creating) ell coins. You can earn transaction fees from verifying Ellcrys transactions.</p>
											</div>

											<div class="article-section">
												<p><span>Ellcrys uses the Blake2b-256 hashing function. You can use CPUs to do the PoW mining.</span></p>
											</div>

											<div class="article-section">
												<p>You will be notified when you mine a block on the notification page and reward will be disbursed to your account.</p>
											</div>
										</div>

										<div class="article">
											<div class="article-section">
												<p>As a Miner, you collect transactions from the pool to create to blocks. When a miner successfully finds a correct proof-of-work nonce for a given block, she sends the candidate block to her peers who then validate and add the blocks to their local chain.</p>
											</div>

											<div class="article-section">
												<p>You typically receive a reward that is roughly proportional to the hashrate of your miner machine (CPU) and the overall hashrate of the network when you commit your computer to PoW mining.</p>
											</div>
										</div>

									</div>

								</div>

								<div class="split-right-footer">
									<button class="next" @click="toNextSlide(4)">Next</button>

									<ul class="page-switcher">
										<li></li>
										<li></li>
										<li  class="active"></li>
										<li></li>
									</ul>

									<button class="skip" @click="doneOnboarding()">Skip</button>
								</div>

							</div>

						</div>

					</div>

				</div>
			</div>
		</transition>

		<transition name="fade">
			<div class="modal-overlay" id="overlay" v-if="open && slide4">
				<div class="modal-pane modal-flex">

					<div class="onboarding-main-split">

						<div class="flex-layout">

							<div class="flex-left split-left onboarding-4-bg">
								<!-- <img src="../../assets/img/Onboarding4.svg" /> -->
							</div>

							<div class="flex-right split-right">

								<h1 class="split-right-header">Safety Tips</h1>

								<div class="split-right-main">
									<div class="article-split-wrapper">

										<div class="article">
											<div class="article-section">
												<p>Only You are responsible for your security. Always keep your seed key and password safe. If you lose them, nobody else can recover it.</p>
											</div>

											<div class="article-section">
												<p><span>When something doesn’t seem right or you don’t understand it, ask questions and do your own research. Avoid making a decision based on fear.</span></p>
											</div>
										</div>

										<div class="article">
											<div class="article-section">
												<p>Do not enter your seed key to any website. Nobody can reverse, cancel or refund transactions if your wallet has been compromised.</p>
											</div>

											<div class="article-section">
												<p>Make a backup of your seed key and password. Don’t store it on your computer, instead write it down or print it out on a piece of paper or save it to a USB drive.</p>
											</div>

										</div>

									</div>

								</div>

								<div class="split-right-footer">
									<button class="next" @click="doneOnboarding()">Done</button>

									<ul class="page-switcher">
										<li></li>
										<li></li>
										<li></li>
										<li class="active"></li>
									</ul>

									<button class="skip" @click="doneOnboarding()">Skip</button>
								</div>

							</div>

						</div>

					</div>

				</div>
			</div>
		</transition>

	</div>
</template>

<script lang="ts">
import { ModalOnBoardingOpen, ModalOnBoardingClose } from '../constants/events';
export default {
	data() {
		return {
			open: false,

			slide1: true,
			slide2: false,
			slide3: false,
			slide4: false,
		};
	},
	created() {
		this.$bus.$on(ModalOnBoardingOpen, seedWords => {
			this.open = true;
		});

		this.$bus.$on(ModalOnBoardingClose, () => {
			this.open = false;
		});
	},
	methods: {
		doneOnboarding() {
			this.$bus.$emit(ModalOnBoardingClose);

			this.slide2 = false;
			this.slide3 = false;
			this.slide4 = false;

			this.slide1 = true;
		},

		toNextSlide(slideNumber: number) {
			this.slide1 = false;
			this.slide2 = false;
			this.slide3 = false;
			this.slide4 = false;

			if (slideNumber === 1) {
				this.slide1 = true;
				return;
			}

			if (slideNumber === 2) {
				this.slide2 = true;
				return;
			}

			if (slideNumber === 3) {
				this.slide3 = true;
				return;
			}

			if (slideNumber === 4) {
				this.slide4 = true;
				return;
			}
		},
	},
};
</script>
