<template>
    <transition name="fade">
        <div class="modal-overlay" id="overlay" v-if="open">
            <div class="modal-pane modal-flex">

                <div class="onboarding-main-split">

                    <div class="flex-layout">

                        <div class="flex-left split-left onboarding-1-bg">

                        </div>
                        <div class="flex-right split-right">

                            <h1 class="split-right-header">What is a wallet?</h1>

                            <div class="split-right-main">
                                <div class="article-split-wrapper">

                                    <div class="article">
                                        <div class="article-section">
                                            <p>Wallet is a feature tool for interacting with the Ellcrys network and using ELL as a currency. You will be able to send and receive ELL coins, as a personal record to track your transactions.</p>
                                        </div>

                                        <div class="article-section">
                                            <p><span>Wallets are often generated by a unique password which creates a seed phrase. The mnemonic seedphrease is a list of 12 words that can be easily written down on paper for backup.</span></p>
                                        </div>
                                    </div>

                                    <div class="article">
                                        <div class="article-section">
                                            <p><span>A seed works as a master key that stores all of the information</span> needed to re-create the wallet at any time even if the encryption passphrase is forgotten or the wallet is destroyed. Same seed can also be used to export your wallet to other Ellcrys wallet clients.</p>
                                        </div>
                                    </div>

                                </div>

                            </div>

                            <div class="split-right-footer">
                                <button class="next">Next</button>

                                <ul class="page-switcher">
                                    <li class="active"></li>
                                    <li></li>
                                    <li></li>
                                    <li></li>
                                </ul>

                                <button class="skip">Skip</button>
                            </div>

                        </div>

                    </div>

                </div>

            </div>
        </div>
    </transition>
</template>

<script lang="ts">
    import {
        ModalOnBoardingOpen,
        ModalOnBoardingClose
    }
    from '../constants/events';
    export default {
        data() {
                return {
                    open: true,
                };
            },
            created() {

                this.$bus.$on(ModalOnBoardingOpen, seedWords => {
                    this.open = true;
                });

                this.$bus.$on(ModalOnBoardingClose, () => {
                    this.open = false;
                });
            },
            methods: {

            },
    };
</script>